#应用运行模式,我们采用了gin框架,目前支持debug/release/test三种
mode:
  debug
#应用的名称,以后扩展,用做应用标识，便于分布式计算
name:
  restgo演示
#应用部署的访问协议,支持http/https两种
protocal:
  http
#应用域名
domain:
  localhost
#请求contextpath
ctxpath:
#服务器绑定的地址
addr:
  0.0.0.0
#端口
port:
  8000
#默认数据资源配置,数据库驱动类型为mysql,详情可以参开xorm
datasource:
    driver_name:
      postgres
    uri:
      "postgres://postgres:postgres@127.0.0.1:5432/userinfo?sslmode=disable"
    max_idle:
      10
    max_open:
      5
    show_sql:
      true

emailsource:
    host:
      ""
    user:
      ""
    password:
      ""
    activateApi:
      ""

